stages:
- release
- build
- deploy

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - ~/.npm/

create_tag:
  image: node:latest
  stage: release
  script:
    - npm i @semantic-release/gitlab
    - npx semantic-release
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - when: always

.ssh_setup: &ssh_setup
- mkdir -p ~/.ssh
- touch ~/.ssh/id_ed25519
- eval "$(ssh-agent -s)"
- cat $SSH_PRIVATE_KEY_B64 | base64 -d | tr -d '\r' > ~/.ssh/id_ed25519
- chmod 700 ~/.ssh/id_ed25519
- cp $SSH_KNOWN_HOSTS ~/.ssh/known_hosts

.ansible_setup: &ansible_setup
  image: lamarr3/ansible-setup:1.0.5
  before_script:
  - *ssh_setup
  - mkdir -p /etc/ansible
  - echo -e "[vms]\n$VM_HOST" > /etc/ansible/hosts
  after_script:
  - rm -rf ~/.ssh
  - rm -rf /etc/ansible

init_vm:
  <<: *ansible_setup
  stage: release
  script:
  - ansible-playbook ansible/playbooks/init-vm-playbook.yaml -u $VM_USER
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - when: manual

build_image:
  <<: *ansible_setup
  stage: build
  script:
  - ansible-playbook ansible/playbooks/build-image-playbook.yaml -u $VM_USER
  rules:
  - if: '$CI_COMMIT_TAG'

update_compose:
  <<: *ansible_setup
  stage: deploy
  script:
  - ansible-playbook ansible/playbooks/update-compose-playbook.yaml -u $VM_USER
  rules:
  - if: '$CI_COMMIT_TAG'

