"""user role mapping

Revision ID: 4a4e7ab377df
Revises: 5a34ac1e3555
Create Date: 2026-03-23 11:31:13.223198

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4a4e7ab377df'
down_revision: Union[str, Sequence[str], None] = '5a34ac1e3555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermodel', sa.Column('role_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'usermodel', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usermodel', type_='foreignkey')
    op.drop_column('usermodel', 'role_id')
    # ### end Alembic commands ###
