"""auth solution sync

Revision ID: daf8cee749be
Revises: 55b036709f33
Create Date: 2026-03-18 13:26:03.512350

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'daf8cee749be'
down_revision: Union[str, Sequence[str], None] = '55b036709f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'refreshsession',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('access_token_id', sa.Uuid(), nullable=False),
        sa.Column('refresh_token_id', sa.Uuid(), nullable=False),
        sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('is_invalidated', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['usermodel.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.add_column(
        'usermodel',
        sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usermodel', 'username')
    op.drop_table('refreshsession')
    # ### end Alembic commands ###
