"""user email

Revision ID: 55b036709f33
Revises: 5e3218b9b7fa
Create Date: 2026-03-10 15:03:39.002421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '55b036709f33'
down_revision: Union[str, Sequence[str], None] = '5e3218b9b7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermodel', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'usermodel', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usermodel', type_='unique')
    op.drop_column('usermodel', 'email')
    # ### end Alembic commands ###
